### PR TITLE
Attempt to get ALaCarteImpl to compile

### PR DESCRIPTION
**Pull request by steshaw**
Hi Mark, I noticed that ALaCarteImpl doesn't compile by default as part of the build. I added it to the .cabal file and attempted to get it to build. I'm still left with some [ambiguous instance errors](https://gist.github.com/steshaw/726db180e5f09a4da2b40b6632f4455b).

Any tips?

### CODE REVIEW

**Comment by mjhopkins** [comment]
Thanks Steven!

I think I missed a commit somewhere.

**Comment by mjhopkins** [comment]
The ambiguous instances come about because I changed `sayHelloProg` to have the more general, open type

```
sayHelloProg :: (Ask :<: f, Tell :<: f) => Free f ()
```

instead of just

```
sayHelloProg :: Free (Ask :+: Tell) ()
```

and forgot to update the code.

GHC complains quite rightly that it doesn't know what more general type we actually want.

**Comment by mjhopkins** [comment]
I'm merged your commit with a small modification to remove the error about ambiguous instances/types.

**Comment by steshaw** [comment]
No worries and thank you! I finally got the program to say "Hello Steven" :D.

**Pull request closed without merging**
